# Site settings
name: 周文涛
email: im.zhouwentao@hotmail.com
author: zhouwentao
url: https://尝试加载css/
resume_site: https://zhouwentao23.github.io/
github: https://github.com/zhouwentao23
baseurl: "/zhouwentao23.github.io"
description: 人生可以暂时苟且，但不能忘了诗和远方
meta_description: 周文涛;个人博客;学而不思则罔;思而不学则殆;生命不止;折腾不休
motto: It's our wits that make us men.
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: zhouwentao23

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

